# Generated by Django 3.2 on 2024-06-01 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('vegetable', '野菜'), ('fruit', '果物'), ('drink', '飲料'), ('frozen_food', '冷凍食品'), ('noodle', '麺'), ('other', 'その他')], max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='SampleModel',
        ),
    ]
