# Generated by Django 3.2 on 2024-06-16 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_food_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='best_by_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
