# Generated by Django 3.2 on 2024-07-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_food_best_by_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='unit',
            field=models.CharField(choices=[('pieces', '個'), ('grams', 'g'), ('milliliter', 'ml')], default='pieces', max_length=100),
        ),
    ]
