# Generated by Django 3.2 on 2024-09-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_food_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('meat', '肉'), ('vegetable', '野菜'), ('fruit', '果物'), ('drink', '飲料'), ('frozen_food', '冷凍食品'), ('noodle', '麺'), ('other', 'その他')], max_length=100),
        ),
    ]
