# Generated by Django 5.1.1 on 2024-10-22 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_alter_food_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('meat', '肉'), ('vegetable', '野菜'), ('fruit', '果物'), ('drink', '飲料'), ('frozen_food', '冷凍食品'), ('noodle', '麺'), ('seasoning', '調味料'), ('other', 'その他')], max_length=100)),
                ('number', models.IntegerField(default=0)),
                ('unit', models.CharField(choices=[('pieces', '個'), ('grams', 'g'), ('milliliter', 'ml')], default='pieces', max_length=100)),
                ('best_by_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
