# Generated by Django 5.1.1 on 2024-10-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_remove_food_template_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food_template',
            name='best_by_date',
        ),
        migrations.AddField(
            model_name='food_template',
            name='day',
            field=models.IntegerField(default=0),
        ),
    ]
